title: Suhui(Susie) Liu # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing Master degree in Data Science at the UW-Madison. 
  <br>
  Actively seeking summer internships in Data Analyst and Data Scientist
  <br><br>
  (608)4210388 | sliu736@wisc.edu
  <br><br>
  <a href="https://www.linkedin.com/in/suhuiliu736/?locale=en_US">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
